### PR TITLE
Begin development page with prerelease testing section

### PR DESCRIPTION
**Pull request by ajnelson-nist**
This PR is posted for TSC review.

# Coordination

- [x] TSC review concluded.
- [x] Visual review of rendered page materials concluded.
- [x] [Nightly builds PR](https://github.com/casework/casework.github.io/pull/156) merged into CASE website after TSC review of this PR's writing.
- [ ] "Hotfix"-style PRs [85](https://github.com/casework/CASE/pull/85) and [86](https://github.com/casework/CASE/pull/86) merged into CASE `master` and `develop` to start `CONTRIBUTE.md`.
- [x] "Hotfix"-style PRs [364](https://github.com/ucoProject/UCO/pull/364) and [365](https://github.com/ucoProject/UCO/pull/365) merged into UCO `master` and `develop` to start `CONTRIBUTE.md`.

### CODE REVIEW

**Comment by ajnelson-nist** [comment]
My current thinking on how this could be linked the ontology repositories:  A file `CONTRIBUTE.md` could be created for each repository, starting with just the following minimal contents (using CASE as an example):

> # Contributing to the CASE ontology
> 
> 
> ## Testing prerelease states
> 
> Practices for users interested in testing prerelease states are documented on the [Cyber Domain Ontology website](https://cyberdomainontologies/ontology/development/#testing-prereleases).

**Comment by ajnelson-nist** [comment]
My current thinking on page division: This PR creates a single, general-purpose "Development" page, accessible at `https://cyberdomainontologies/ontology/development/` (designed so `index.*` doesn't need to be typed), and relies on page anchors to direct reader attention.  Here's the next ways I expect the pool of development resources to grow:

* For *developers of the ontologies*: Adding a "Versioning" discussion to encompass SEMVER usage
* For *developers and consumers of the ontologies*: Discussing the branching models used in CASE and UCO repositories.  The ontologies and CASE tools use Git-flow.  CASE-Examples and the websites use continual-release.  It'd be nice to be able to give these a brief name and general practices description we could link to in all of the repositories.
* For *consumers of the ontologies*: Testing with SHACL, in a section coming just before what's been drafted in this PR.
* For *consumers of the ontologies*: Possibly migrating the [CASE instance data guidance page](https://caseontology.org/resources/instance_data.html) into this page.  (IIRC, that's just HTML because I didn't know about customizable page anchor syntax in Markdown, so it doesn't need to remain HTML.)

Given that expansion, does it make sense to maintain a single `index.md`?

**Comment by ajnelson-nist** [comment]
For people using the Github Issues templates we're drafting, I thought of a couple other items that would be good to have on this page:
* Some "Stock" competency statements, like we'd need to address many `ObservableObject` `rdfs:range` and `sh:class` refinements.
* The coordination checklist for change proposals
* The review checklist for pull requests into `develop`

**Comment by ajnelson-nist** [comment]
Now that UCO has merged its CONTRIBUTE.md update, the website should have this page available.

**Review by regriff — APPROVED** [review]

**Pull request merged**
